In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [5]:
%cd '/content/gdrive/MyDrive/sbs/핵심역량프로젝트/재은/D'
!ls

/content/gdrive/.shortcut-targets-by-id/13UT7pZKq5f5I3_As8dIyogN3Up9BH8R9/00_sbs/핵심역량프로젝트/재은/D
그래프		     청소년d.ipynb  체지방률-회귀.ipynb		teen4.csv
지역간거리두기.csv.  E		    OWID_KOREA_COVID데이터.csv	Untitled0.ipynb

In [6]:
teen_df = pd.read_csv('/content/gdrive/MyDrive/sbs/핵심역량프로젝트/재은/D/teen4.csv')

In [7]:
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80

In [8]:
!pip install html_table_parser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting html_table_parser
  Downloading html_table_parser-0.1.0.tar.gz (3.4 kB)
Collecting beautifulsoup4==4.4.1
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 9.2 MB/s
Building wheels for collected packages: html-table-parser
  Building wheel for html-table-parser (setup.py) ... done
  Created wheel for html-table-parser: filename=html_table_parser-0.1.0-py3-none-any.whl size=4645 sha256=748ad6165192a64c48aa9698675f1d217c42e46446881547dd6aadb5a8439773
  Stored in directory: /root/.cache/pip/wheels/8b/db/ba/ffbb0a5dcb78fd955a33d26295a77ced593e712a7d8a4a0dc6
Successfully built html-table-parser
Installing collected packages: beautifulsoup4, html-table-parser
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed beautifulsoup4-4.4.1 html-table-parser-0.1.0

In [9]:
!pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.4.1)

In [10]:
!pip install --upgrade beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.4.1)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 29.1 MB/s
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.4.1
    Uninstalling beautifulsoup4-4.4.1:
      Successfully uninstalled beautifulsoup4-4.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
html-table-parser 0.1.0 requires beautifulsoup4==4.4.1, but you have beautifulsoup4 4.11.1 which is incompatible.
Successfully installed beautifulsoup4-4.11.1 soupsieve-2.3.2.post1

In [11]:
!pip install --upgrade html5lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: html5lib in /usr/local/lib/python3.7/dist-packages (1.0.1)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 39.0 MB/s
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from html5lib) (1.15.0)
Installing collected packages: html5lib
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
Successfully installed html5lib-1.1

In [12]:
!pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.9.1)

In [13]:
!pip install html5lib==0.9999999

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting html5lib==0.9999999
  Downloading html5lib-0.9999999.tar.gz (889 kB)
     |████████████████████████████████| 889 kB 36.5 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from html5lib==0.9999999) (1.15.0)
Building wheels for collected packages: html5lib
  Building wheel for html5lib (setup.py) ... done
  Created wheel for html5lib: filename=html5lib-0.9999999-py3-none-any.whl size=107234 sha256=d5ef4a528ffb4351525cd586e791d4b066ee83683b6eb91a9588d78595ba5794
  Stored in directory: /root/.cache/pip/wheels/53/8d/2f/a9d4c8e58cffde4e60ba7f8aac7495de9bc12cffdc2f947723
Successfully built html5lib
Installing collected packages: html5lib
  Attempting uninstall: html5lib
    Found existing installation: html5lib 1.1
    Uninstalling html5lib-1.1:
      Successfully uninstalled html5lib-1.1
Successfully installed html5lib-0.9999999

In [14]:
import requests
from bs4 import BeautifulSoup
from html_table_parser import parser_functions

req = requests.get('https://nfa.kspo.or.kr/front/control/con0901_list.do')
soup = BeautifulSoup(req.text, 'html.parser')
data = soup.find('table', {'class':'List8'})
table = parser_functions.make2d(data)
grade_df = pd.DataFrame(data=table)

In [15]:
grade_df

,0,1,2,3,4,5,6,7,8
0,구분,항목,분류,남학생,남학생,남학생,여학생,여학생,여학생
1,구분,항목,분류,위험,개선,건강,위험,개선,건강
2,심폐지구력(택1),20m왕복오래달리기(횟수),13세,≤21,22-34,≥35,≤14,15-22,≥23
3,심폐지구력(택1),20m왕복오래달리기(횟수),14세,≤24,25-40,≥41,≤14,15-22,≥23
4,심폐지구력(택1),20m왕복오래달리기(횟수),15세,≤25,26-42,≥43,≤14,15-22,≥23
5,심폐지구력(택1),20m왕복오래달리기(횟수),16세,≤25,26-43,≥44,≤14,15-22,≥23
6,심폐지구력(택1),20m왕복오래달리기(횟수),17세,≤25,26-43,≥44,≤14,15-23,≥24
7,심폐지구력(택1),20m왕복오래달리기(횟수),18세,≤25,26-43,≥44,≤14,15-24,≥25
8,심폐지구력(택1),최대산소섭취량(ml/kg/min),13세,≤38.2,38.3-41.1,≥41.2,≤32.2,32.3-34.3,≥34.4
9,심폐지구력(택1),최대산소섭취량(ml/kg/min),14세,≤39.0,39.1-42.0,≥42.1,≤32.1,32.2-34.2,≥34.3
10,심폐지구력(택1),최대산소섭취량(ml/kg/min),15세,≤39.0,39.1-42.2,≥42.3,≤31.8,31.9-34.0,≥34.1
11,심폐지구력(택1),최대산소섭취량(ml/kg/min),16세,≤39.0,39.1-42.1,≥42.2,≤31.5,31.6-33.8,≥33.9
12,심폐지구력(택1),최대산소섭취량(ml/kg/min),17세,≤39.0,39.1-42.2,≥42.3,≤31.6,31.7-34.0,≥34.1
13,심폐지구력(택1),최대산소섭취량(ml/kg/min),18세,≤39.0,39.1-42.1,≥42.2,≤32.0,32.1-34.5,≥34.6
14,근력,상대악력(%),13세,≤38.3,38.4-44.7,≥44.8,≤33.5,33.6-43.2,≥43.3
15,근력,상대악력(%),14세,≤41.4,41.5-48.1,≥48.2,≤33.6,33.7-43.7,≥43.8
16,근력,상대악력(%),15세,≤44.1,44.2-51.2,≥51.3,≤33.0,33.1-43.3,≥43.4
17,근력,상대악력(%),16세,≤46.1,46.2-53.5,≥53.6,≤32.3,32.4-43.0,≥43.1
18,근력,상대악력(%),17세,≤47.1,47.2-54.5,≥54.6,≤33.4,33.5-44.8,≥44.9
19,근력,상대악력(%),18세,≤47.7,47.8-55.0,≥55.1,≤35.0,35.1-47.0,≥47.1

In [16]:
grade_df.rename(columns={1:'ITEM', 2:'TEST_AGE', 3:'M_위험', 4:'M_개선', 5:'M_건강', 6:'F_위험', 7:'F_개선', 8:'F_건강' }, inplace=True)

In [17]:
grade_df

,0,ITEM,TEST_AGE,M_위험,M_개선,M_건강,F_위험,F_개선,F_건강
0,구분,항목,분류,남학생,남학생,남학생,여학생,여학생,여학생
1,구분,항목,분류,위험,개선,건강,위험,개선,건강
2,심폐지구력(택1),20m왕복오래달리기(횟수),13세,≤21,22-34,≥35,≤14,15-22,≥23
3,심폐지구력(택1),20m왕복오래달리기(횟수),14세,≤24,25-40,≥41,≤14,15-22,≥23
4,심폐지구력(택1),20m왕복오래달리기(횟수),15세,≤25,26-42,≥43,≤14,15-22,≥23
5,심폐지구력(택1),20m왕복오래달리기(횟수),16세,≤25,26-43,≥44,≤14,15-22,≥23
6,심폐지구력(택1),20m왕복오래달리기(횟수),17세,≤25,26-43,≥44,≤14,15-23,≥24
7,심폐지구력(택1),20m왕복오래달리기(횟수),18세,≤25,26-43,≥44,≤14,15-24,≥25
8,심폐지구력(택1),최대산소섭취량(ml/kg/min),13세,≤38.2,38.3-41.1,≥41.2,≤32.2,32.3-34.3,≥34.4
9,심폐지구력(택1),최대산소섭취량(ml/kg/min),14세,≤39.0,39.1-42.0,≥42.1,≤32.1,32.2-34.2,≥34.3
10,심폐지구력(택1),최대산소섭취량(ml/kg/min),15세,≤39.0,39.1-42.2,≥42.3,≤31.8,31.9-34.0,≥34.1
11,심폐지구력(택1),최대산소섭취량(ml/kg/min),16세,≤39.0,39.1-42.1,≥42.2,≤31.5,31.6-33.8,≥33.9
12,심폐지구력(택1),최대산소섭취량(ml/kg/min),17세,≤39.0,39.1-42.2,≥42.3,≤31.6,31.7-34.0,≥34.1
13,심폐지구력(택1),최대산소섭취량(ml/kg/min),18세,≤39.0,39.1-42.1,≥42.2,≤32.0,32.1-34.5,≥34.6
14,근력,상대악력(%),13세,≤38.3,38.4-44.7,≥44.8,≤33.5,33.6-43.2,≥43.3
15,근력,상대악력(%),14세,≤41.4,41.5-48.1,≥48.2,≤33.6,33.7-43.7,≥43.8
16,근력,상대악력(%),15세,≤44.1,44.2-51.2,≥51.3,≤33.0,33.1-43.3,≥43.4
17,근력,상대악력(%),16세,≤46.1,46.2-53.5,≥53.6,≤32.3,32.4-43.0,≥43.1
18,근력,상대악력(%),17세,≤47.1,47.2-54.5,≥54.6,≤33.4,33.5-44.8,≥44.9
19,근력,상대악력(%),18세,≤47.7,47.8-55.0,≥55.1,≤35.0,35.1-47.0,≥47.1

In [18]:
grade_df.drop([0], axis=1, inplace=True)
grade_df

,ITEM,TEST_AGE,M_위험,M_개선,M_건강,F_위험,F_개선,F_건강
0,항목,분류,남학생,남학생,남학생,여학생,여학생,여학생
1,항목,분류,위험,개선,건강,위험,개선,건강
2,20m왕복오래달리기(횟수),13세,≤21,22-34,≥35,≤14,15-22,≥23
3,20m왕복오래달리기(횟수),14세,≤24,25-40,≥41,≤14,15-22,≥23
4,20m왕복오래달리기(횟수),15세,≤25,26-42,≥43,≤14,15-22,≥23
5,20m왕복오래달리기(횟수),16세,≤25,26-43,≥44,≤14,15-22,≥23
6,20m왕복오래달리기(횟수),17세,≤25,26-43,≥44,≤14,15-23,≥24
7,20m왕복오래달리기(횟수),18세,≤25,26-43,≥44,≤14,15-24,≥25
8,최대산소섭취량(ml/kg/min),13세,≤38.2,38.3-41.1,≥41.2,≤32.2,32.3-34.3,≥34.4
9,최대산소섭취량(ml/kg/min),14세,≤39.0,39.1-42.0,≥42.1,≤32.1,32.2-34.2,≥34.3
10,최대산소섭취량(ml/kg/min),15세,≤39.0,39.1-42.2,≥42.3,≤31.8,31.9-34.0,≥34.1
11,최대산소섭취량(ml/kg/min),16세,≤39.0,39.1-42.1,≥42.2,≤31.5,31.6-33.8,≥33.9
12,최대산소섭취량(ml/kg/min),17세,≤39.0,39.1-42.2,≥42.3,≤31.6,31.7-34.0,≥34.1
13,최대산소섭취량(ml/kg/min),18세,≤39.0,39.1-42.1,≥42.2,≤32.0,32.1-34.5,≥34.6
14,상대악력(%),13세,≤38.3,38.4-44.7,≥44.8,≤33.5,33.6-43.2,≥43.3
15,상대악력(%),14세,≤41.4,41.5-48.1,≥48.2,≤33.6,33.7-43.7,≥43.8
16,상대악력(%),15세,≤44.1,44.2-51.2,≥51.3,≤33.0,33.1-43.3,≥43.4
17,상대악력(%),16세,≤46.1,46.2-53.5,≥53.6,≤32.3,32.4-43.0,≥43.1
18,상대악력(%),17세,≤47.1,47.2-54.5,≥54.6,≤33.4,33.5-44.8,≥44.9
19,상대악력(%),18세,≤47.7,47.8-55.0,≥55.1,≤35.0,35.1-47.0,≥47.1

In [19]:
grade_df.drop([0, 1], axis=0, inplace=True)

In [20]:
grade_df['TEST_AGE'].replace('세', '', regex=True, inplace=True)
grade_df['TEST_AGE']

2     13
3     14
4     15
5     16
6     17
7     18
8     13
9     14
10    15
11    16
12    17
13    18
14    13
15    14
16    15
17    16
18    17
19    18
Name: TEST_AGE, dtype: object

In [21]:
type(grade_df['TEST_AGE'][2])

str

In [22]:
grade_df.replace('20m왕복오래달리기(횟수)', 'ITEM_F020', inplace=True)

In [23]:
grade_df.replace('최대산소섭취량(ml/kg/min)', 'ITEM_F035/ITEM_F037', inplace=True)

In [24]:
grade_df.replace('상대악력(%)', 'ITEM_F028', inplace=True)

In [25]:
grade_df

,ITEM,TEST_AGE,M_위험,M_개선,M_건강,F_위험,F_개선,F_건강
2,ITEM_F020,13,≤21,22-34,≥35,≤14,15-22,≥23
3,ITEM_F020,14,≤24,25-40,≥41,≤14,15-22,≥23
4,ITEM_F020,15,≤25,26-42,≥43,≤14,15-22,≥23
5,ITEM_F020,16,≤25,26-43,≥44,≤14,15-22,≥23
6,ITEM_F020,17,≤25,26-43,≥44,≤14,15-23,≥24
7,ITEM_F020,18,≤25,26-43,≥44,≤14,15-24,≥25
8,ITEM_F035/ITEM_F037,13,≤38.2,38.3-41.1,≥41.2,≤32.2,32.3-34.3,≥34.4
9,ITEM_F035/ITEM_F037,14,≤39.0,39.1-42.0,≥42.1,≤32.1,32.2-34.2,≥34.3
10,ITEM_F035/ITEM_F037,15,≤39.0,39.1-42.2,≥42.3,≤31.8,31.9-34.0,≥34.1
11,ITEM_F035/ITEM_F037,16,≤39.0,39.1-42.1,≥42.2,≤31.5,31.6-33.8,≥33.9
12,ITEM_F035/ITEM_F037,17,≤39.0,39.1-42.2,≥42.3,≤31.6,31.7-34.0,≥34.1
13,ITEM_F035/ITEM_F037,18,≤39.0,39.1-42.1,≥42.2,≤32.0,32.1-34.5,≥34.6
14,ITEM_F028,13,≤38.3,38.4-44.7,≥44.8,≤33.5,33.6-43.2,≥43.3
15,ITEM_F028,14,≤41.4,41.5-48.1,≥48.2,≤33.6,33.7-43.7,≥43.8
16,ITEM_F028,15,≤44.1,44.2-51.2,≥51.3,≤33.0,33.1-43.3,≥43.4
17,ITEM_F028,16,≤46.1,46.2-53.5,≥53.6,≤32.3,32.4-43.0,≥43.1
18,ITEM_F028,17,≤47.1,47.2-54.5,≥54.6,≤33.4,33.5-44.8,≥44.9
19,ITEM_F028,18,≤47.7,47.8-55.0,≥55.1,≤35.0,35.1-47.0,≥47.1

In [26]:
grade_df['M_위험'].replace('≤', '', regex=True, inplace=True)  # 이하

In [27]:
grade_df['F_위험'].replace('≤', '', regex=True, inplace=True)  # 이하

In [28]:
grade_df

,ITEM,TEST_AGE,M_위험,M_개선,M_건강,F_위험,F_개선,F_건강
2,ITEM_F020,13,21,22-34,≥35,14,15-22,≥23
3,ITEM_F020,14,24,25-40,≥41,14,15-22,≥23
4,ITEM_F020,15,25,26-42,≥43,14,15-22,≥23
5,ITEM_F020,16,25,26-43,≥44,14,15-22,≥23
6,ITEM_F020,17,25,26-43,≥44,14,15-23,≥24
7,ITEM_F020,18,25,26-43,≥44,14,15-24,≥25
8,ITEM_F035/ITEM_F037,13,38.2,38.3-41.1,≥41.2,32.2,32.3-34.3,≥34.4
9,ITEM_F035/ITEM_F037,14,39.0,39.1-42.0,≥42.1,32.1,32.2-34.2,≥34.3
10,ITEM_F035/ITEM_F037,15,39.0,39.1-42.2,≥42.3,31.8,31.9-34.0,≥34.1
11,ITEM_F035/ITEM_F037,16,39.0,39.1-42.1,≥42.2,31.5,31.6-33.8,≥33.9
12,ITEM_F035/ITEM_F037,17,39.0,39.1-42.2,≥42.3,31.6,31.7-34.0,≥34.1
13,ITEM_F035/ITEM_F037,18,39.0,39.1-42.1,≥42.2,32.0,32.1-34.5,≥34.6
14,ITEM_F028,13,38.3,38.4-44.7,≥44.8,33.5,33.6-43.2,≥43.3
15,ITEM_F028,14,41.4,41.5-48.1,≥48.2,33.6,33.7-43.7,≥43.8
16,ITEM_F028,15,44.1,44.2-51.2,≥51.3,33.0,33.1-43.3,≥43.4
17,ITEM_F028,16,46.1,46.2-53.5,≥53.6,32.3,32.4-43.0,≥43.1
18,ITEM_F028,17,47.1,47.2-54.5,≥54.6,33.4,33.5-44.8,≥44.9
19,ITEM_F028,18,47.7,47.8-55.0,≥55.1,35.0,35.1-47.0,≥47.1

In [29]:
grade_df['M_건강'].replace('≥', '', regex=True, inplace=True)  # 이상

In [30]:
grade_df['F_건강'].replace('≥', '', regex=True, inplace=True)  # 이상

In [31]:
grade_df

                   ITEM TEST_AGE  M_위험       M_개선  M_건강  F_위험       F_개선  F_건강
2             ITEM_F020       13    21      22-34    35    14      15-22    23
3             ITEM_F020       14    24      25-40    41    14      15-22    23
4             ITEM_F020       15    25      26-42    43    14      15-22    23
5             ITEM_F020       16    25      26-43    44    14      15-22    23
6             ITEM_F020       17    25      26-43    44    14      15-23    24
7             ITEM_F020       18    25      26-43    44    14      15-24    25
8   ITEM_F035/ITEM_F037       13  38.2  38.3-41.1  41.2  32.2  32.3-34.3  34.4
9   ITEM_F035/ITEM_F037       14  39.0  39.1-42.0  42.1  32.1  32.2-34.2  34.3
10  ITEM_F035/ITEM_F037       15  39.0  39.1-42.2  42.3  31.8  31.9-34.0  34.1
11  ITEM_F035/ITEM_F037       16  39.0  39.1-42.1  42.2  31.5  31.6-33.8  33.9
12  ITEM_F035/ITEM_F037       17  39.0  39.1-42.2  42.3  31.6  31.7-34.0  34.1
13  ITEM_F035/ITEM_F037       18  39.0  39.1-42.1  42.2  32.0  32.1-34.5  34.6
14            ITEM_F028       13  38.3  38.4-44.7  44.8  33.5  33.6-43.2  43.3
15            ITEM_F028       14  41.4  41.5-48.1  48.2  33.6  33.7-43.7  43.8
16            ITEM_F028       15  44.1  44.2-51.2  51.3  33.0  33.1-43.3  43.4
17            ITEM_F028       16  46.1  46.2-53.5  53.6  32.3  32.4-43.0  43.1
18            ITEM_F028       17  47.1  47.2-54.5  54.6  33.4  33.5-44.8  44.9
19            ITEM_F028       18  47.7  47.8-55.0  55.1  35.0  35.1-47.0  47.1

In [32]:
grade_df = grade_df.reset_index(drop=True)

In [33]:
grade_df['TEST_AGE'] = grade_df['TEST_AGE'].apply(lambda x: float(x))

In [34]:
shuttle_run = grade_df[grade_df['ITEM'] == 'ITEM_F020']
t_s = grade_df[grade_df['ITEM'] == 'ITEM_F035/ITEM_F037']
strength = grade_df[grade_df['ITEM'] == 'ITEM_F028']

In [35]:
shuttle_run

        ITEM  TEST_AGE M_위험   M_개선 M_건강 F_위험   F_개선 F_건강
0  ITEM_F020     13.00   21  22-34   35   14  15-22   23
1  ITEM_F020     14.00   24  25-40   41   14  15-22   23
2  ITEM_F020     15.00   25  26-42   43   14  15-22   23
3  ITEM_F020     16.00   25  26-43   44   14  15-22   23
4  ITEM_F020     17.00   25  26-43   44   14  15-23   24
5  ITEM_F020     18.00   25  26-43   44   14  15-24   25

In [36]:
shuttle_run.drop(['ITEM'], axis=1, inplace=True)
shuttle_run

   TEST_AGE M_위험   M_개선 M_건강 F_위험   F_개선 F_건강
0     13.00   21  22-34   35   14  15-22   23
1     14.00   24  25-40   41   14  15-22   23
2     15.00   25  26-42   43   14  15-22   23
3     16.00   25  26-43   44   14  15-22   23
4     17.00   25  26-43   44   14  15-23   24
5     18.00   25  26-43   44   14  15-24   25

In [37]:
shuttle_run = shuttle_run.reset_index(drop=True)

In [38]:
shuttle_run

   TEST_AGE M_위험   M_개선 M_건강 F_위험   F_개선 F_건강
0     13.00   21  22-34   35   14  15-22   23
1     14.00   24  25-40   41   14  15-22   23
2     15.00   25  26-42   43   14  15-22   23
3     16.00   25  26-43   44   14  15-22   23
4     17.00   25  26-43   44   14  15-23   24
5     18.00   25  26-43   44   14  15-24   25

In [39]:
t_s.drop(['ITEM'], axis=1, inplace=True)
t_s

    TEST_AGE  M_위험       M_개선  M_건강  F_위험       F_개선  F_건강
6      13.00  38.2  38.3-41.1  41.2  32.2  32.3-34.3  34.4
7      14.00  39.0  39.1-42.0  42.1  32.1  32.2-34.2  34.3
8      15.00  39.0  39.1-42.2  42.3  31.8  31.9-34.0  34.1
9      16.00  39.0  39.1-42.1  42.2  31.5  31.6-33.8  33.9
10     17.00  39.0  39.1-42.2  42.3  31.6  31.7-34.0  34.1
11     18.00  39.0  39.1-42.1  42.2  32.0  32.1-34.5  34.6

In [40]:
t_s = t_s.reset_index(drop=True)
t_s

   TEST_AGE  M_위험       M_개선  M_건강  F_위험       F_개선  F_건강
0     13.00  38.2  38.3-41.1  41.2  32.2  32.3-34.3  34.4
1     14.00  39.0  39.1-42.0  42.1  32.1  32.2-34.2  34.3
2     15.00  39.0  39.1-42.2  42.3  31.8  31.9-34.0  34.1
3     16.00  39.0  39.1-42.1  42.2  31.5  31.6-33.8  33.9
4     17.00  39.0  39.1-42.2  42.3  31.6  31.7-34.0  34.1
5     18.00  39.0  39.1-42.1  42.2  32.0  32.1-34.5  34.6

In [41]:
strength.drop(['ITEM'], axis=1, inplace=True)
strength

    TEST_AGE  M_위험       M_개선  M_건강  F_위험       F_개선  F_건강
12     13.00  38.3  38.4-44.7  44.8  33.5  33.6-43.2  43.3
13     14.00  41.4  41.5-48.1  48.2  33.6  33.7-43.7  43.8
14     15.00  44.1  44.2-51.2  51.3  33.0  33.1-43.3  43.4
15     16.00  46.1  46.2-53.5  53.6  32.3  32.4-43.0  43.1
16     17.00  47.1  47.2-54.5  54.6  33.4  33.5-44.8  44.9
17     18.00  47.7  47.8-55.0  55.1  35.0  35.1-47.0  47.1

In [42]:
strength = strength.reset_index(drop=True)
strength

   TEST_AGE  M_위험       M_개선  M_건강  F_위험       F_개선  F_건강
0     13.00  38.3  38.4-44.7  44.8  33.5  33.6-43.2  43.3
1     14.00  41.4  41.5-48.1  48.2  33.6  33.7-43.7  43.8
2     15.00  44.1  44.2-51.2  51.3  33.0  33.1-43.3  43.4
3     16.00  46.1  46.2-53.5  53.6  32.3  32.4-43.0  43.1
4     17.00  47.1  47.2-54.5  54.6  33.4  33.5-44.8  44.9
5     18.00  47.7  47.8-55.0  55.1  35.0  35.1-47.0  47.1

In [43]:
shuttle_dict = {}

for i in range(shuttle_run.shape[0]):
    age = shuttle_run.iloc[i,0]
    a = str(shuttle_run.iloc[i,1])
    b = shuttle_run.iloc[i, 2].split('-')[0]
    c = shuttle_run.iloc[i, 2].split('-')[1]
    d = str(shuttle_run.iloc[i,3])
    e = str(shuttle_run.iloc[i,4])
    f = shuttle_run.iloc[i, 5].split('-')[0]
    g = shuttle_run.iloc[i, 5].split('-')[1]
    h = str(shuttle_run.iloc[i,6])
    shuttle_dict[age] = {0: (float(a), float(b), float(c), float(d)), 1: (float(e), float(f), float(g), float(h))}

shuttle_dict[13]

{0: (21.0, 22.0, 34.0, 35.0), 1: (14.0, 15.0, 22.0, 23.0)}

In [44]:
ts_dict = {}

for i in range(t_s.shape[0]):
    age = t_s.iloc[i,0]
    a = str(t_s.iloc[i,1])
    b = t_s.iloc[i, 2].split('-')[0]
    c = t_s.iloc[i, 2].split('-')[1]
    d = str(t_s.iloc[i,3])
    e = str(t_s.iloc[i,4])
    f = t_s.iloc[i, 5].split('-')[0]
    g = t_s.iloc[i, 5].split('-')[1]
    h = str(t_s.iloc[i,6])
    ts_dict[age] = {0: (float(a), float(b), float(c), float(d)), 1: (float(e), float(f), float(g), float(h))}

ts_dict[13]

{0: (38.2, 38.3, 41.1, 41.2), 1: (32.2, 32.3, 34.3, 34.4)}

In [45]:
strength_dict = {}

for i in range(strength.shape[0]):
    age = strength.iloc[i,0]
    a = str(strength.iloc[i,1])
    b = strength.iloc[i, 2].split('-')[0]
    c = strength.iloc[i, 2].split('-')[1]
    d = str(strength.iloc[i,3])
    e = str(strength.iloc[i,4])
    f = strength.iloc[i, 5].split('-')[0]
    g = strength.iloc[i, 5].split('-')[1]
    h = str(strength.iloc[i,6])
    strength_dict[age] = {0: (float(a), float(b), float(c), float(d)), 1: (float(e), float(f), float(g), float(h))}

strength_dict[13]

{0: (38.3, 38.4, 44.7, 44.8), 1: (33.5, 33.6, 43.2, 43.3)}

In [ ]:
# 위험: 0, 개선: 1, 건강: 2

In [46]:
def shuttlerun_grade(age, sex, run_score):
    a, b, c, d = shuttle_dict[age][sex]
    if run_score <= a:
        return '위험'
    elif b <= run_score <= c:
        return '개선'
    elif run_score >= d:
        return '건강'
    else:
        return '이상치'

def treadmill_grade(age, sex, t_score):
    a, b, c, d = ts_dict[age][sex]
    if t_score <= a:
        return '위험'
    elif b <= t_score <= c:
        return '개선'
    elif t_score >= d:
        return '건강'
    else:
        return '이상치'

def step_grade(age, sex, s_score):
    a, b, c, d = ts_dict[age][sex]
    if s_score <= a:
        return '위험'
    elif b <= s_score <= c:
        return '개선'
    elif s_score >= d:
        return '건강'
    else:
        return '이상치'

def gripstrength_grade(age, sex, g_score):
    a, b, c, d = strength_dict[age][sex]
    if g_score <= a:
        return '위험'
    elif b <= g_score <= c:
        return '개선'
    elif g_score >= d:
        return '건강'
    else:
        return '이상치'

In [47]:
심폐지구력_등급 = []
근력_등급 = []

for i in teen_df.index:
    age = teen_df.loc[i, '나이']
    sex = teen_df.loc[i, '성별']
    run_score = int(teen_df.loc[i, '심폐지구력'])
    g_score = int(teen_df.loc[i, '근력'])

    심폐지구력_등급.append(shuttlerun_grade(age, sex, run_score))
    근력_등급.append(gripstrength_grade(age, sex, g_score))

In [48]:
teen_df['심폐지구력_등급'] = 심폐지구력_등급
teen_df['근력_등급'] = 근력_등급

In [49]:
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력,심폐지구력_등급,근력_등급
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50,개선,개선
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40,위험,위험
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40,개선,건강
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20,위험,위험
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30,건강,위험
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10,건강,개선
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70,개선,개선
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60,건강,건강
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70,건강,건강
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80,건강,건강

In [50]:
teen_df.isnull().sum()

Datetime    0
년           0
월           0
일           0
요일          0
회차          0
나이          0
성별          0
신장          0
체중          0
체지방률        0
이완기혈압       0
수축기혈압       0
BMI         0
유연성(cm)     0
일리노이        0
체공시간        0
협응력         0
심폐지구력       0
근력          0
심폐지구력_등급    0
근력_등급       0
dtype: int64

In [51]:
teen_df.shape

(303113, 22)

In [52]:
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력,심폐지구력_등급,근력_등급
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50,개선,개선
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40,위험,위험
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40,개선,건강
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20,위험,위험
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30,건강,위험
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10,건강,개선
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70,개선,개선
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60,건강,건강
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70,건강,건강
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80,건강,건강

In [53]:
# bmi 등급 나누기

def bmi_grade(bmi):
    if bmi <= 18.5:
        return 0 # 저체중
    elif 18.5 < bmi <= 23.:
        return 1 # 정상
    elif 23. < bmi <= 25.:
        return 2 # 과체중
    elif 25. < bmi <= 35:
        return 3 # 비만
    else :
        return 4 # 고도비만
    # else:
    #     return 'who are you?'

def male_bodyfat_grade(bodyfat):
    if bodyfat < 10:
        return 0 # 저체중
    elif 10 <= bodyfat < 21.:
        return 1 # 정상
    elif 21 < bodyfat <= 25.:
        return 2 # 과체중
    elif 25. < bodyfat <= 35.:
        return 3 # 비만
    else :
        return 4 #고도비만
    # else:
    #     return 'who are you?'

def female_bodyfat_grade(bodyfat):
    if bodyfat < 18:
        return 0 # 저체중
    elif 18 <= bodyfat < 25.:
        return 1 # 정상
    elif 25 < bodyfat <= 30.:
        return 2 # 과체중
    elif 30. < bodyfat <= 40.:
        return 3 # 비만
    else:
        return 4 # 고도비만
    # else:
    #     return 'who are you?'

In [54]:
teen_df['BMI_등급'] = teen_df['BMI'].apply(bmi_grade)

In [55]:
teen_df['BMI_등급'].value_counts()

1    141733
3     68588
0     46283
2     43831
4      2678
Name: BMI_등급, dtype: int64

In [56]:
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력,심폐지구력_등급,근력_등급,BMI_등급
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50,개선,개선,1
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40,위험,위험,3
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40,개선,건강,2
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20,위험,위험,3
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30,건강,위험,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10,건강,개선,1
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70,개선,개선,1
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60,건강,건강,1
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70,건강,건강,1
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80,건강,건강,1

In [57]:
teen_df['체지방률_등급'] = None

In [58]:
teen_df['체지방률_등급'][teen_df['성별']==0] = teen_df['체지방률'][teen_df['성별']==0].apply(male_bodyfat_grade)
teen_df['체지방률_등급'][teen_df['성별']==1] = teen_df['체지방률'][teen_df['성별']==1].apply(female_bodyfat_grade)
teen_df['체지방률_등급'].isnull().sum()

0

In [59]:
teen_df.head()
teen_df['체지방률_등급'].value_counts()

1.00    106788
3.00    100705
2.00     55782
4.00     25861
0.00     13977
Name: 체지방률_등급, dtype: int64

In [60]:
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력,심폐지구력_등급,근력_등급,BMI_등급,체지방률_등급
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50,개선,개선,1,1.00
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40,위험,위험,3,3.00
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40,개선,건강,2,1.00
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20,위험,위험,3,4.00
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30,건강,위험,1,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10,건강,개선,1,1.00
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70,개선,개선,1,2.00
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60,건강,건강,1,1.00
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70,건강,건강,1,3.00
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80,건강,건강,1,1.00

In [61]:
grade_num = teen_df['체지방률_등급'].value_counts().sort_index()
grade_num.rename(index={0.: "저체중", 1.:"정상체중", 2.:"과체중", 3.:"비만", 4.:"고도비만"}, inplace=True)
grade_num

저체중      13977
정상체중    106788
과체중      55782
비만      100705
고도비만     25861
Name: 체지방률_등급, dtype: int64

In [62]:
teen_df['체지방률_등급'] = teen_df['체지방률_등급'].replace({0.: "저체중", 1.:"정상체중", 2.:"과체중", 3.:"비만", 4.:"고도비만"})
teen_df

,Datetime,년,월,일,요일,회차,나이,성별,신장,체중,체지방률,이완기혈압,수축기혈압,BMI,유연성(cm),일리노이,체공시간,협응력,심폐지구력,근력,심폐지구력_등급,근력_등급,BMI_등급,체지방률_등급
0,2018-01-02,2018,1,2,Tuesday,1,15.00,0,179.60,64.50,14.70,53.00,106.00,20.00,6.00,19.22,0.51,52.38,40.00,50.50,개선,개선,1,정상체중
1,2018-01-02,2018,1,2,Tuesday,1,17.00,0,173.50,88.30,31.10,74.00,130.00,29.30,2.00,21.26,0.39,72.28,20.00,45.40,위험,위험,3,비만
2,2018-01-02,2018,1,2,Tuesday,1,17.00,0,176.30,74.98,16.90,85.00,153.00,24.10,14.60,17.46,0.60,48.35,33.00,57.40,개선,건강,2,정상체중
3,2018-01-02,2018,1,2,Tuesday,1,18.00,0,167.70,82.90,35.80,86.00,127.00,29.50,16.80,25.56,0.38,51.00,18.00,35.20,위험,위험,3,고도비만
4,2018-01-02,2018,1,2,Tuesday,1,15.00,0,175.70,69.20,23.70,93.00,135.00,22.40,5.00,19.04,0.51,50.93,44.00,42.30,건강,위험,1,과체중
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303108,2022-05-30,2022,5,30,Monday,2,18.00,0,177.70,70.90,20.20,77.00,142.00,22.50,6.30,17.46,0.54,48.30,60.98,55.10,건강,개선,1,정상체중
303109,2022-05-30,2022,5,30,Monday,1,18.00,1,165.50,60.80,29.80,71.00,109.00,22.20,31.50,19.21,0.51,75.29,23.00,46.70,개선,개선,1,과체중
303110,2022-05-30,2022,5,30,Monday,2,16.00,1,167.60,61.50,22.70,62.00,139.00,21.90,13.70,19.86,0.50,55.48,32.00,63.60,건강,건강,1,정상체중
303111,2022-05-30,2022,5,30,Monday,1,16.00,1,152.80,49.70,30.60,72.00,123.00,21.30,15.30,21.14,0.45,43.99,31.00,50.70,건강,건강,1,비만
303112,2022-05-30,2022,5,30,Monday,1,15.00,0,158.60,50.20,14.00,77.00,121.00,20.00,15.60,20.69,0.74,51.31,62.29,59.80,건강,건강,1,정상체중

In [63]:
teen_df.to_csv('/content/gdrive/MyDrive/sbs/핵심역량프로젝트/t_data.csv', index = None)